version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis: # <-- НОВЫЙ СЕРВИС REDIS
    image: redis:6-alpine # Используем легковесный образ Redis
    ports:
      - "6379:6379" # Опционально: открываем порт для прямого доступа с хоста
    volumes:
      - redis_data:/data # Для персистентности данных Redis (если нужно)

  web:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis # <-- ЗАВИСИМОСТЬ ОТ REDIS
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:mysecretpassword@db/postgres"
      SECRET_KEY: "super-secret-jwt-key-change-this-in-production"
      REDIS_HOST: redis # <-- НОВАЯ ПЕРЕМЕННАЯ ОКРУЖЕНИЯ
      REDIS_PORT: 6379 # <-- НОВАЯ ПЕРЕМЕННАЯ ОКРУЖЕНИЯ

volumes:
  postgres_data:
  redis_data: # <-- НОВЫЙ VOLUME